Allow Choices Option
doctify/model-base pull request #4
Opened 2017-01-10 12:37 UTC by devotox

This allows us to have an array of possible choices and if the value is not one of those choices in the array an error is thrown

2017-01-11 14:19 UTC, bill-edwards approved these changes
Looks good to me.

2017-01-11 15:18 UTC, thehogfather reviewed
one question about the intended logic  when `type is not function`. Otherwise looks fine.

2017-01-11 15:18 UTC, thehogfather commented on lib/model.js
>  const flattenArray = ModelUtilities.flattenArray;
for your next changes, destructuring is your friend :)

2017-01-11 15:18 UTC, thehogfather commented on lib/model.js
>  			value = ( type !== 'function' && isFunction(value) ) ? value(key, type) : value;
just checking this is the intended logic - type is not function so we go ahead and invoke it as a function?

2017-01-11 17:08 UTC, rafaelalvessa requested changes

2017-01-11 17:08 UTC, rafaelalvessa commented on lib/model.js
> +		if(!ModelValidator[attr.type](this[key], attr.options)){ return `${key} should be of type ${attr.type}`; }
Add a space before `{`.

2017-01-11 17:08 UTC, rafaelalvessa commented on lib/model.js
> +		if( attr.choices && attr.choices.length &&
Remove extra space before `attr.choices`.

2017-01-11 17:08 UTC, rafaelalvessa commented on lib/model.js
> +			{ return `${key} of type ${attr.type} should be one of ${attr.choices}`; }
Fix indentation in lines 306-307.

2017-01-12 20:07 UTC, devotox commented on lib/model.js
>  			value = ( type !== 'function' && isFunction(value) ) ? value(key, type) : value;
yes basically if the type is function then it means we should test the value to be a function but if its not a function and it sees value as a function it runs it

2017-01-12 22:13 UTC, merged